### ISSUE TITLE
Explain watermarks

### ISSUE THREAD

**Issue by DanielJonesEB** [FidelityInternational/diego-capacity-monitor#2]
Hey Fiddlers,

We've got a customer who'd benefit from using this. Perusing the README, it's not super-clear exactly what a watermark is, and what values a user should set. I've thought about it for at least 45 seconds, and I'm still none-the-wiser.

Is it the number of Diego cells/percentage of Diego cells you could lose without running out of RAMs in the remaining parts of the cluster?

**Comment by sambryant4** [comment]
@DanielJonesEB does the version of the README in 4f40656 help?

**Comment by andrewdriver123** [comment]
Readme enhanced in September to make things clearer.
